### ISSUE TITLE
Where to put the shortcode to show the bage.

### ISSUE THREAD

**Issue by shoaibhassan** [strangerstudios/pmpro-member-badges#2]
Hi ,i need to know where i can put this shortcode to show badge on profile picture .

**Comment by kimcoleman** [comment]
The shortcode can be placed in any page or post. I do not know what your "profile picture" is - if you mean to overlay the badge with the avatar, you'll need a developer to help you with that. It may be possible using the WordPress avatar function and a filter to that display.

**Comment by shoaibhassan** [comment]
I message this years ago.

>
